<?php
	$slide_status = $this->getResponsivebannersliderEnabled();   
	$slide_speed = $this->getResponsivebannersliderSpeed();   
	$slide_BannerLoop = $this->getResponsivebannerBannerLoop(); 
	$slide_PauseOnhover = $this->getResponsivebannerPauseOnhover();
	$jquery_enable = $this->getResponsivebannerJqueryEnable();
	$enableDescription = $this->getResponsivebannerDescription();
	$pagination = $this->getResponsivebannerPagination();
	$controls = $this->getResponsivebannerControls();

?>

<?php if($slide_status): ?>

		<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('responsiveslider/css/generic-nav.css'); ?>" media="all">
		<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('responsiveslider/css/grid12.css'); ?>" media="all">

		<?php if($jquery_enable): ?>
			<script type="text/javascript" src="<?php echo $this->getSkinUrl('responsiveslider/js/jquery-1.js'); ?>"></script>
			<script type="text/javascript" src="<?php echo $this->getSkinUrl('responsiveslider/js/jquery-noconflict.js'); ?>"></script>
		<?php endif; ?>

		<script type="text/javascript" src="<?php echo $this->getSkinUrl('responsiveslider/js/jquery_004.js'); ?>"></script>
		<script type="text/javascript" src="<?php echo $this->getSkinUrl('responsiveslider/js/jquery_003.js'); ?>"></script>
	 
		<div class="the-slideshow-wrapper nested-container clearer">
			<div class="the-slideshow gen-slider-arrows2 gen-slider-pager1 gen-slider-pager1-pos-bottom-right grid12-9  ">

				<ul class="slides">
				<?php
                    $sliderCollection = Mage::getModel('responsivebannerslider/responsivebannerslider')->getCollection()
                            ->addFieldToFilter('status', 1)
                            ->setOrder('imageorder','ASC')
                            ->load();
                ?>

                <?php foreach($sliderCollection as $item): ?>
                    <?php $media_url =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>
                    <?php $img_url = $media_url.$item->getImage(); ?>
                        <li style="width: 100%; float: left; margin-right: -100%; position: relative; display: none;" class="slide" onclick="">
                            <a href="<?php echo $item->getUrl(); ?>">
                                <img src="<?php echo $img_url; ?>" alt="<?php echo $item->getTitle(); ?>" title="<?php echo $item->getTitle(); ?>">
                                <?php if($enableDescription): ?>
                                    <div class="caption">
                                        <h2><?php echo $item->getDescription(); ?></h2>
                                    </div>
                                <?php endif; ?>
                            </a>
                        </li>
                <?php endforeach; ?>
				</ul>
			 
			</div>
		</div>

		<script type="text/javascript">
		//<![CDATA[
			responsivebanner = jQuery.noConflict(); 
			responsivebanner(window).load(function(){
				responsivebanner('.the-slideshow').flexslider({
					namespace:"",
					animation:'slide',
					easing:'easeInOutCirc',
					useCSS:	false,
					animationLoop:<?php echo $slide_BannerLoop; ?>,
					smoothHeight: true,
					slideshowSpeed:<?php echo $slide_speed; ?>,
					animationSpeed:	600,
					controlNav: <?php echo $pagination; ?>,
					directionNav: <?php echo $controls; ?>,
					pauseOnHover:<?php echo $slide_PauseOnhover; ?>
				});
			});
		//]]>
		</script>    

<?php else: ?>

	<h1 style="color:red;">Enable ( Banner Slider ) Module via Admin = System -> Configuration-> Wagento -> Banner Slider </h1>

<?php endif; ?>
 
